# Generated by Django 4.1.6 on 2023-02-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, verbose_name='enter your first name')),
                ('lastname', models.CharField(max_length=10, verbose_name='enter your first name')),
                ('Email', models.EmailField(max_length=254, verbose_name='enter your email')),
                ('phn_no', models.IntegerField(verbose_name='enter your phone number')),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
